workflows:
  android:
    name: Android Workflow
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      android_signing:
        - my_keystore
      vars:
        PACKAGE_NAME: "com.example.multicountdowntimer"
    scripts:
      - name: Build APK
        script: | 
          ./gradlew assembleRelease
    artifacts:
      - app/build/outputs/**/*.apk
